%YAML:1.0
---
# model file path
model_path: "../apps/model/bottle_cut.pcd"
# model size
model_size: {
    x: 0.0387,
    y: 0.1160,
    z: 0.0383
    }
# uniform sampling radius
uniform_radius: 0.006
# icp guess with yaw = {2pi/divide_num, 2*2pi/divide_num, ..., 2pi}
divide_num: 12
iter_num: 0